# Generated by Django 5.2.10 on 2026-02-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classbased', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
