# Generated by Django 5.2.10 on 2026-02-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbased', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
